export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";

export const OBTENER_PRODUCTO = "OBTENER_PRODUCTO";
export const OBTENER_PRODUCTO_EXITO = "OBTENER_PRODUCTO_EXITO";
export const OBTENER_PRODUCTO_ERROR = "OBTENER_PRODUCTO_ERROR";
